# Generated by Django 2.2.6 on 2019-10-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20191006_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postname',
        ),
    ]
