# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-02 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now=True, default=datetime.datetime(2019, 10, 2, 14, 6, 9, 302795, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
